<?php
session_start(); include("conexion.php");
if (!isset($_SESSION["usuario_id"])) { header("Location: login.php"); exit(); }
if (!isset($_GET["id"])) { header("Location: explorador.php"); exit(); }
$idPlantilla=intval($_GET["id"]);
$consulta=$conexion->prepare("SELECT plantillas.*, usuarios.nombre AS nombre_usuario FROM plantillas INNER JOIN usuarios ON plantillas.id_usuario = usuarios.id WHERE plantillas.id = ?"); $consulta->bind_param("i",$idPlantilla); $consulta->execute(); $resultado=$consulta->get_result(); if($resultado->num_rows===0){die("Plantilla no encontrada.");} $plantilla=$resultado->fetch_assoc();
$consultaArchivos=$conexion->prepare("SELECT * FROM archivos_plantilla WHERE id_plantilla = ?"); $consultaArchivos->bind_param("i",$idPlantilla); $consultaArchivos->execute(); $archivos=$consultaArchivos->get_result(); $contenidoArchivo="";
if(isset($_GET["archivo"])){ $idArchivo=intval($_GET["archivo"]); $consultaArchivo=$conexion->prepare("SELECT * FROM archivos_plantilla WHERE id = ? AND id_plantilla = ?"); $consultaArchivo->bind_param("ii",$idArchivo,$idPlantilla); $consultaArchivo->execute(); $resultadoArchivo=$consultaArchivo->get_result(); if($resultadoArchivo->num_rows===1){ $archivoSeleccionado=$resultadoArchivo->fetch_assoc(); if(file_exists($archivoSeleccionado["ruta_archivo"])){ $contenidoArchivo=file_get_contents($archivoSeleccionado["ruta_archivo"]); }}}
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?php echo htmlspecialchars($plantilla["nombre"]); ?> - GetInWeb</title><link rel="stylesheet" href="php_extra.css"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap" rel="stylesheet"></head><body><header><div class="header-contenido"><div class="marca"><h2 class="logotipo">GetInWeb</h2><span>Archivos de plantilla</span></div><nav class="menu"><ul><ol><a href="explorador.php">Explorador</a></ol><ol><a href="Personalizador/index.html">Generador</a></ol></ul></nav><a href="logout.php" class="btn-cerrar">Cerrar sesión</a></div></header><main class="detalle-main"><section class="detalle-plantilla"><div class="detalle-imagen"><img src="<?php echo htmlspecialchars($plantilla["imagen_preview"]); ?>" alt="Preview"></div><div class="detalle-info"><span><?php echo htmlspecialchars($plantilla["categoria"]); ?></span><h1><?php echo htmlspecialchars($plantilla["nombre"]); ?></h1><p><?php echo htmlspecialchars($plantilla["descripcion"]); ?></p><small>Subido por: <?php echo htmlspecialchars($plantilla["nombre_usuario"]); ?></small><div class="detalle-botones"><a href="explorador.php" class="btn-secundario">Volver</a><a href="Personalizador/index.html" class="btn-generador">Usar plantilla</a></div></div></section><section class="archivos-seccion"><h2>Archivos subidos</h2><div class="lista-archivos"><?php while($archivo=$archivos->fetch_assoc()) { ?><a class="archivo-btn" href="plantilla.php?id=<?php echo $idPlantilla; ?>&archivo=<?php echo $archivo["id"]; ?>"><?php echo htmlspecialchars($archivo["nombre_original"]); ?></a><?php } ?></div><pre class="visor-codigo"><?php echo $contenidoArchivo !== "" ? htmlspecialchars($contenidoArchivo) : "Seleccioná un archivo para ver su contenido."; ?></pre></section></main></body></html>
